"""Criar tabelas edicoes e consumos

Revision ID: f6f50e7d20d6
Revises: 
Create Date: 2025-08-05 19:44:09.224225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6f50e7d20d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consumos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('consumos_edicao_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'edicoes', ['edicao_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consumos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('consumos_edicao_id_fkey'), 'edicoes', ['edicao_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
